# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    labels:
      - dependencies
    commit-message:
      prefix: chore
      include: scope
    groups:
      browser-runtimes:
        patterns:
          - "onnxruntime-web"
          - "@vladmandic/human"
          - "@tensorflow/tfjs-backend-wasm"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
      - github-actions
